### ISSUE TITLE
Test fail with OpenSSL 3

### ISSUE THREAD

**Issue by espen** [elct9620/rails-letsencrypt#37]
Encountered an error while trying to do some changes to this gem.

```
  1) LetsEncrypt::Certificate#active? return true when certificate exists
     Failure/Error: certificate.present?
     
     OpenSSL::X509::CertificateError:
       ASN1 lib
     # ./app/models/lets_encrypt/certificate.rb:44:in `active?'
     # ./spec/models/lets_encrypt/certificate_spec.rb:16:in `block (3 levels) in <top (required)>'
```

Using openssl v 2.2.3 works.

Looks like OpenSSL v3 will fail for empty certificate: `OpenSSL::X509::Certificate.new` used in certificate_spec.rb. Yields a certificate when doing `to_s` on 2.2.3 but not in 3.x.

**Comment by elct9620** [comment]
https://github.com/ruby/openssl/issues/369

Seems have some issue to support OpenSSL 3 🤔
